---
- name: install apache
  apt: name=apache2 update_cache=yes cache_valid_time=86400 state=present

- name: replace config file
  copy:
    src=config/virtualhost.conf
    dest=/etc/apache2/sites-available/000-default.conf
    mode=0644
  notify:
    - restart apache

- name: enable mod_rewrite
  apache2_module: name=rewrite state=present

- name: delete default apache directory
  file: path=/var/www/html state=absent